SUBSUBMOD:=$(shell basename $(CURDIR)).a
#BINDIR = $(RIOTBASE)/bin/
SRC = $(wildcard *.c)
OBJ = $(SRC:%.c=$(BINDIR)%.o)
DEP = $(SRC:%.c=$(BINDIR)%.d)

INCLUDES += -I$(RIOTBASE) -I$(RIOTBASE)/sys/include -I$(RIOTBASE)/core/include -I$(RIOTBASE)/drivers/include -I$(RIOTBASE)/drivers/cc110x_ng/include -I$(RIOTBASE)/cpu/arm_common/include -I$(RIOTBASE)/sys/net/include/
INCLUDES += -I$(CURDIR)/02a-MAClow
INCLUDES += -I$(CURDIR)/02b-MAChigh
INCLUDES += -I$(CURDIR)/03a-IPHC
INCLUDES += -I$(CURDIR)/03b-IPv6
INCLUDES += -I$(CURDIR)/04-TRAN
INCLUDES += -I$(CURDIR)/cross-layers

.PHONY: $(BINDIR)$(SUBSUBMOD)

$(BINDIR)$(SUBSUBMOD): $(OBJ)
	$(AD)$(AR) rcs $(BINDIR)$(MODULE) $(OBJ)

# pull in dependency info for *existing* .o files
-include $(OBJ:.o=.d)

# compile and generate dependency info
$(BINDIR)%.o: %.c
	$(AD)$(CC) $(CFLAGS) $(INCLUDES) $(BOARDINCLUDE) $(PROJECTINCLUDE) $(CPUINCLUDE) -c $*.c -o $(BINDIR)$*.o
	$(AD)$(CC) $(CFLAGS) $(INCLUDES) $(BOARDINCLUDE) $(PROJECTINCLUDE) $(CPUINCLUDE) -MM $*.c > $(BINDIR)$*.d
	@printf "$(BINDIR)" | cat - $(BINDIR)$*.d > /tmp/riot_out && mv /tmp/riot_out $(BINDIR)$*.d

# remove compilation products

clean:
	rm -f $(OBJ) $(DEP)
